package authgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/repooooo/auth-service/internal/transport/http/graph/auth/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginRequest) (*model.LoginResponse, error) {
	//TODO: validator for request
	success, message, token, err := r.auth.Login(ctx, input.Username, input.Password)
	if err != nil {
		return nil, err
	}

	return &model.LoginResponse{
		Success: success,
		Message: message,
		Token:   token,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.LogoutRequest) (*model.LogoutResponse, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
